name: "Setup Python environment"

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -e '.[dev]'
