name: Continuous Integration
run-name: Continuous Integration (${{ github.event.pull_request.title || github.event.commits[0].message }})

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_MINIMAL_VERSION: "3.12"
  PYTHON_VERSIONS: '["3.12", "3.13"]'

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ env.PYTHON_MINIMAL_VERSION }}
    - name: Format with ruff
      run: |
        ruff format --diff

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ env.PYTHON_MINIMAL_VERSION }}
    - name: Lint with ruff
      run: |
        ruff check

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(env.PYTHON_VERSIONS) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with pytest
      run: |
        pytest -vv

  types:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(env.PYTHON_VERSIONS) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Analyze types with mypy
      run: |
        mypy .
