name: Continuous Integration
run-name: Continuous Integration (${{ github.event.pull_request.title || github.event.commits[0].message }})

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.python-versions.outputs.python-versions }}
    steps:
    - id: python-versions
      run: |
        echo 'python-versions=["3.12", "3.13"]' >> "$GITHUB_OUTPUT"

  format:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python-versions) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Format with ruff
      run: |
        ruff format --diff

  lint:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python-versions) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with ruff
      run: |
        ruff check

  test:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python-versions) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with pytest
      run: |
        pytest -vv

  types:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python-versions) }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Analyze types with mypy
      run: |
        mypy .
